# Generated by Django 5.2.16 on 2026-07-28 09:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMonitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='ID сессии')),
                ('user_public_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='public_id пользователя')),
                ('user_label', models.CharField(blank=True, default='', max_length=255, verbose_name='Пользователь (снимок)')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('language', models.CharField(blank=True, default='', max_length=32, verbose_name='Язык')),
                ('timezone', models.CharField(blank=True, default='', max_length=64, verbose_name='Часовой пояс')),
                ('viewport', models.CharField(blank=True, default='', max_length=32, verbose_name='Viewport')),
                ('client_version', models.CharField(blank=True, default='', max_length=64, verbose_name='Версия клиента')),
                ('scope_claim_keys', models.JSONField(blank=True, default=list, verbose_name='Ключи session-scope claims')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Начало')),
                ('last_event_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Последнее событие')),
                ('has_errors', models.BooleanField(db_index=True, default=False, verbose_name='Есть ошибки')),
                ('event_count', models.PositiveIntegerField(default=0, verbose_name='Число событий')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_monitor_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия мониторинга клиента',
                'verbose_name_plural': 'Сессии мониторинга клиентов',
                'ordering': ['-last_event_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientMonitorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(verbose_name='Порядковый номер')),
                ('kind', models.CharField(choices=[('nav', 'Навигация'), ('api', 'API'), ('error', 'Ошибка'), ('warn', 'Предупреждение'), ('lifecycle', 'Жизненный цикл')], db_index=True, max_length=16, verbose_name='Тип')),
                ('created_at', models.DateTimeField(db_index=True, verbose_name='Время клиента')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время приёма')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core_client_monitor.clientmonitorsession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Событие мониторинга клиента',
                'verbose_name_plural': 'События мониторинга клиентов',
                'ordering': ['session_id', 'seq'],
            },
        ),
        migrations.AddIndex(
            model_name='clientmonitorsession',
            index=models.Index(fields=['has_errors', '-last_event_at'], name='cm_sess_err_last_idx'),
        ),
        migrations.AddIndex(
            model_name='clientmonitorsession',
            index=models.Index(fields=['user', '-last_event_at'], name='cm_sess_user_last_idx'),
        ),
        migrations.AddIndex(
            model_name='clientmonitorevent',
            index=models.Index(fields=['session', 'seq'], name='cm_event_sess_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='clientmonitorevent',
            index=models.Index(fields=['kind', 'created_at'], name='cm_event_kind_created_idx'),
        ),
        migrations.AddIndex(
            model_name='clientmonitorevent',
            index=models.Index(fields=['created_at'], name='cm_event_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientmonitorevent',
            constraint=models.UniqueConstraint(fields=('session', 'seq'), name='cm_event_session_seq_uniq'),
        ),
    ]
