# Generated by Django 5.2.3 on 2025-06-18 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _create_default_data(apps, schema_editor):
    """Начальные PermissionMark и базовые auth-маршруты CMS (заморожено для миграции)."""
    PermissionMark = apps.get_model('cms', 'PermissionMark')
    CMSPage = apps.get_model('cms', 'CMSPage')

    permission_marks = [
        {'name': 'ComponentAccessionToRead', 'id': 1},
        {'name': 'ComponentAccessionToReadAndWrite', 'id': 2},
        {'name': 'PageAccession', 'id': 3},
        {'name': 'AdminAccession', 'id': 4},
    ]

    for mark_data in permission_marks:
        PermissionMark.objects.get_or_create(
            id=mark_data['id'],
            defaults={'name': mark_data['name']},
        )

    initial_paths = (
        '/',
        '/logout',
        '/start-page',
        '/login',
        '/register',
        '/forgot-password',
        '/reset-password',
        '/two-steps',
    )
    for path in initial_paths:
        CMSPage.objects.get_or_create(path=path)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='', max_length=255)),
                ('liminationtype', models.CharField(choices=[('withliminations', 'Страница с ограничениями'), ('withoutliminations', 'Страница без ограничений'), ('closepage', 'Закрытая страница')], default='withoutliminations', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GroupCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Object_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CMSPageComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componentid', models.CharField(default='', max_length=255)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.cmspage')),
            ],
        ),
        migrations.CreateModel(
            name='ExpandedPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('group_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.groupcategory')),
                ('permission_mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.permissionmark')),
            ],
        ),
        migrations.CreateModel(
            name='Accession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.cmspage')),
                ('component_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.cmspagecomponent')),
                ('permission', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cms.expandedpermission')),
            ],
        ),
        migrations.CreateModel(
            name='ExpandedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.groupcategory')),
            ],
        ),
        migrations.CreateModel(
            name='GroupURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=255)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectlink', models.CharField(default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.object_type')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('rating', models.IntegerField(default=0)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        
        migrations.RunPython(_create_default_data),
    ]
