# Generated by Django 5.2.16 on 2026-08-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_rename_cmspage_page_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('module_name', models.CharField(blank=True, default='core', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API-эндпоинт',
                'verbose_name_plural': 'API-эндпоинты',
                'ordering': ['path'],
            },
        ),
    ]
