# Generated by Django 5.2.16 on 2026-08-01 18:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


FORK_AUTH_MIGRATIONS = (
    '0013_add_user_middle_name',
    '0014_add_user_public_id',
)

REMOVED_ROUTE_NAMES = (
    'SiteSettings',
    'Shortcodes',
    'MainShortcodePage',
    'Templates',
    'Pages',
    'Layouts',
    'PageShortcodeCategories',
    'Categories',
    'PageCategories',
    'PageCategoriesManager',
    'TagsManager',
)

REMOVED_MODULE_SOURCES = (
    'core/shortcodes',
    'cms_shortcodes',
    'core/categories',
)

ROUTE_NAME = 'AuditLogPanel'
NEW_ROUTE_NAME = 'AccessControlPanel'
MODULE_SOURCE = 'core/cms'
GRADUATE_EMPLOYMENT_MODULE_SOURCE = 'modules/graduate_employment'
MODULE_NAME = 'graduate_employment'
ROLE_GROUP_TEACHER = 'Преподаватель (НН)'
ROLE_GROUP_STUDENT = 'Студент (НН)'


def _column_exists(cursor, vendor, table_name, column_name):
    if vendor == 'sqlite':
        cursor.execute(f'PRAGMA table_info("{table_name}")')
        return any(col[1] == column_name for col in cursor.fetchall())
    if vendor == 'postgresql':
        cursor.execute(
            """
            SELECT EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_schema = CURRENT_SCHEMA()
                  AND table_name = %s
                  AND column_name = %s
            )
            """,
            [table_name, column_name],
        )
        return cursor.fetchone()[0]
    return False


def _add_column_if_missing(cursor, vendor, table_name, column_name, column_sql):
    if _column_exists(cursor, vendor, table_name, column_name):
        return
    if vendor == 'sqlite':
        cursor.execute(
            f'ALTER TABLE "{table_name}" ADD COLUMN "{column_name}" {column_sql}'
        )
        return
    cursor.execute(
        f'ALTER TABLE "{table_name}" ADD COLUMN IF NOT EXISTS '
        f'"{column_name}" {column_sql}'
    )


def ensure_ergo_user_table(apps, schema_editor):
    """Создаёт auth_user (+ M2M), если таблицы ещё нет (fresh install).

    В database_operations SeparateDatabaseAndState historical apps ещё без
    ErgoUser (CreateModel только в state_operations) — берём установленную модель.
    """
    from django.apps import apps as global_apps

    ErgoUser = global_apps.get_model('cms_adp', 'ErgoUser')
    table_name = ErgoUser._meta.db_table
    existing = set(schema_editor.connection.introspection.table_names())
    if table_name in existing:
        return
    schema_editor.create_model(ErgoUser)


def create_system_roles(apps, schema_editor):
    """
    Создаёт базовые системные роли: 'Пользователь' и 'Администратор'.
    Использует SQL для корректной работы с наследованием от Group.
    Кроссплатформенное решение для SQLite и PostgreSQL.
    """
    from django.db import connection
    from django.utils import timezone
    
    roles_to_create = [
        ('Пользователь', 'Роль по умолчанию для всех пользователей', True),
        ('Администратор', 'Системная роль с полным доступом', True),
    ]
    
    # Получаем текущее время
    now = timezone.now()
    
    # Определяем тип БД для правильного синтаксиса
    vendor = connection.vendor
    
    with connection.cursor() as cursor:
        for name, description, is_system in roles_to_create:
            # Проверяем, существует ли уже Group с таким именем
            cursor.execute("SELECT id FROM auth_group WHERE name = %s", [name])
            row = cursor.fetchone()
            
            if row:
                group_id = row[0]
            else:
                # Создаём Group (кроссплатформенный подход)
                if vendor == 'postgresql':
                    # PostgreSQL поддерживает RETURNING
                    cursor.execute(
                        "INSERT INTO auth_group (name) VALUES (%s) RETURNING id",
                        [name]
                    )
                    group_id = cursor.fetchone()[0]
                else:
                    # SQLite и другие - используем lastrowid
                    cursor.execute(
                        "INSERT INTO auth_group (name) VALUES (%s)",
                        [name]
                    )
                    group_id = cursor.lastrowid
                    if not group_id:
                        # Если lastrowid не сработал, делаем SELECT
                        cursor.execute("SELECT id FROM auth_group WHERE name = %s", [name])
                        group_id = cursor.fetchone()[0]
            
            # Проверяем, существует ли Role
            cursor.execute(
                "SELECT group_ptr_id FROM cms_adp_role WHERE group_ptr_id = %s",
                [group_id]
            )
            if not cursor.fetchone():
                # Создаём Role с текущим временем как параметром (Django автоматически конвертирует datetime)
                cursor.execute("""
                    INSERT INTO cms_adp_role (group_ptr_id, description, is_system, created_at, updated_at)
                    VALUES (%s, %s, %s, %s, %s)
                """, [group_id, description, is_system, now, now])
            else:
                # Обновляем is_system, если роль уже существует
                cursor.execute("""
                    UPDATE cms_adp_role 
                    SET is_system = %s, description = %s, updated_at = %s
                    WHERE group_ptr_id = %s
                """, [is_system, description, now, group_id])


def delete_system_roles(apps, schema_editor):
    """Обратная миграция - удаляем системные роли."""
    from django.db import connection
    
    with connection.cursor() as cursor:
        for name in ['Пользователь', 'Администратор']:
            cursor.execute("SELECT id FROM auth_group WHERE name = %s", [name])
            row = cursor.fetchone()
            if row:
                cursor.execute("DELETE FROM cms_adp_role WHERE group_ptr_id = %s", [row[0]])


def remove_middle_name_field_safe(apps, schema_editor):
    """
    Безопасно удаляет поле middle_name из UserProfile, если оно существует.
    Если поля нет - ничего не делает.
    Кроссплатформенное решение для SQLite и PostgreSQL.
    """
    from django.db import connection
    
    vendor = connection.vendor
    table_name = 'cms_adp_userprofile'
    column_name = 'middle_name'
    field_exists = False
    
    with connection.cursor() as cursor:
        # Проверяем существование колонки в зависимости от типа БД
        if vendor == 'sqlite':
            # Для SQLite используем PRAGMA table_info
            # PRAGMA не поддерживает параметризованные запросы, но имя таблицы контролируется нами
            cursor.execute(f'PRAGMA table_info("{table_name}")')
            columns = cursor.fetchall()
            # В PRAGMA table_info структура: (cid, name, type, notnull, default_value, pk)
            field_exists = any(col[1] == column_name for col in columns)
        elif vendor == 'postgresql':
            # Для PostgreSQL используем information_schema
            cursor.execute("""
                SELECT EXISTS (
                    SELECT 1 
                    FROM information_schema.columns 
                    WHERE table_schema = 'public' 
                    AND table_name = %s
                    AND column_name = %s
                )
            """, [table_name, column_name])
            field_exists = cursor.fetchone()[0]
        else:
            # Для других БД пытаемся использовать DROP COLUMN IF EXISTS
            # (большинство современных БД поддерживают это)
            try:
                cursor.execute(f"ALTER TABLE {table_name} DROP COLUMN IF EXISTS {column_name}")
                field_exists = True  # Предполагаем, что поле могло существовать
            except Exception:
                field_exists = False
        
        if field_exists:
            # Поле существует - удаляем его
            try:
                # Используем DROP COLUMN для разных БД
                if vendor == 'sqlite':
                    # SQLite 3.35.0+ поддерживает DROP COLUMN
                    # Для старых версий будет ошибка, но это не критично
                    cursor.execute(f'ALTER TABLE "{table_name}" DROP COLUMN "{column_name}"')
                else:
                    # PostgreSQL и другие БД - используем IF EXISTS
                    cursor.execute(f'ALTER TABLE "{table_name}" DROP COLUMN IF EXISTS "{column_name}"')
                print(f"[INFO] Поле {column_name} удалено из таблицы {table_name}.")
            except Exception as e:
                # Если не удалось удалить (старая версия SQLite или поле уже удалено)
                print(f"[INFO] Не удалось удалить поле {column_name}: {e}. Возможно, поле уже не существует или используется старая версия SQLite.")


def add_middle_name_field_back(apps, schema_editor):
    """
    Обратная миграция - добавляет поле middle_name обратно, если его нет.
    Кроссплатформенное решение для SQLite и PostgreSQL.
    """
    from django.db import connection
    
    vendor = connection.vendor
    table_name = 'cms_adp_userprofile'
    column_name = 'middle_name'
    field_exists = False
    
    with connection.cursor() as cursor:
        # Проверяем существование колонки в зависимости от типа БД
        if vendor == 'sqlite':
            # Для SQLite используем PRAGMA table_info
            # PRAGMA не поддерживает параметризованные запросы, но имя таблицы контролируется нами
            cursor.execute(f'PRAGMA table_info("{table_name}")')
            columns = cursor.fetchall()
            field_exists = any(col[1] == column_name for col in columns)
        elif vendor == 'postgresql':
            # Для PostgreSQL используем information_schema
            cursor.execute("""
                SELECT EXISTS (
                    SELECT 1 
                    FROM information_schema.columns 
                    WHERE table_schema = 'public' 
                    AND table_name = %s
                    AND column_name = %s
                )
            """, [table_name, column_name])
            field_exists = cursor.fetchone()[0]
        else:
            # Для других БД пытаемся добавить колонку (будет ошибка, если уже существует)
            field_exists = False
        
        if not field_exists:
            # Поле не существует - добавляем его обратно
            try:
                # Все БД поддерживают ADD COLUMN
                cursor.execute(f"""
                    ALTER TABLE "{table_name}" 
                    ADD COLUMN "{column_name}" VARCHAR(150) NULL;
                """)
                print(f"[INFO] Поле {column_name} добавлено обратно в таблицу {table_name}.")
            except Exception as e:
                # Поле уже существует или произошла ошибка
                print(f"[INFO] Не удалось добавить поле {column_name}: {e}")
        else:
            print(f"[INFO] Поле {column_name} уже существует в таблице {table_name}. Пропускаем добавление.")


def populate_core_menu(apps, schema_editor):
    """Создаёт базовые элементы меню из core модулей."""
    from src.core.cms.adp.menu.migration_utils import MenuMigrationHelper
    
    # === CMS ===
    cms = MenuMigrationHelper(apps, 'core/cms')
    cms.clear_module_items()
    
    # Разделители
    cms.create_separator('Настройки', before_order=0)
    cms.create_separator('Модули', before_order=20)
    
    # Личный кабинет (фиксированный order=0)
    user_menu = cms.create_group('Личный кабинет', 'User', icon='CircleUserRound', order=0)
    cms.create_routes_batch([
        ('Профиль', 'Account'),
    ], parent=user_menu)
    
    # Настройки сайта (фиксированный order=10)
    settings_menu = cms.create_group(
        'Настройки сайта',
        'Settings',
        icon='UserCog',
        order=10,
        is_admin_only=True,
    )
    admin_panel = cms.create_group(
        'Админ-панель',
        'AdminPanel',
        icon='KeySquare',
        parent=settings_menu,
        order=10,
        is_admin_only=True,
    )
    users_menu = cms.create_group(
        'Пользователи',
        'UsersPanel',
        icon='Users',
        parent=admin_panel,
        order=10,
    )
    cms.create_routes_batch([
        ('В сети', 'OnlineUsersPanel'),
    ], parent=users_menu)
    cms.create_routes_batch([
        ('Роли', 'CategoriesPanel'),
        ('Ролевые группы', 'GroupsPanel'),
        ('Политики и права', 'PermissionsPanel'),
        ('Ограничения', 'LiminationPanel'),
        ('Управление меню', 'MenuPanel'),
    ], parent=admin_panel)
    cms.create_route(
        'Темы оформления',
        'ThemeEditor',
        parent=settings_menu,
        icon='Palette',
        order=20,
        is_admin_only=True,
    )
    
    # Остальные настройки — удалены: общие настройки, редактор страниц, категории страниц


def reverse_populate_core_menu(apps, schema_editor):
    """Удаляет элементы меню из core модулей."""
    MenuItem = apps.get_model('cms_adp', 'MenuItem')
    MenuSeparator = apps.get_model('cms_adp', 'MenuSeparator')
    
    MenuItem.objects.filter(module_source__startswith='core/').delete()
    MenuSeparator.objects.all().delete()


def add_theme_editor_menu(apps, schema_editor):
    """Добавляет элементы меню для редактора тем."""
    from src.core.cms.adp.menu.migration_utils import MenuMigrationHelper
    
    # Получаем модель MenuItem
    MenuItem = apps.get_model('cms_adp', 'MenuItem')
    
    # Находим родительский элемент "Настройки сайта"
    settings_menu = MenuItem.objects.filter(
        route_name='Settings',
        module_source='core/cms'
    ).first()
    
    if not settings_menu:
        return
    
    # Создаем хелпер для редактора тем
    theme_editor = MenuMigrationHelper(apps, 'core/cms')
    
    # Создаем группу "Темы оформления"
    theme_settings = theme_editor.create_group(
        'Темы оформления', 'ThemeSettings', 
        icon='Palette', 
        parent=settings_menu
    )
    
    # Создаем дочерний элемент "Редактор тем"
    theme_editor.create_route(
        'Редактор тем', 'ThemeEditor',
        parent=theme_settings,
        icon='Palette'
    )


def remove_theme_editor_menu(apps, schema_editor):
    """Удаляет элементы меню для редактора тем."""
    MenuItem = apps.get_model('cms_adp', 'MenuItem')
    
    # Удаляем элементы меню редактора тем
    MenuItem.objects.filter(
        route_name__in=['ThemeSettings', 'ThemeEditor'],
        module_source='core/cms'
    ).delete()


def add_neural_networks_hub_menu(apps, schema_editor):
    """
    Раньше сидел меню neural_networks_hub в ядре.

    Seed модуля должен жить только в миграциях самого модуля. Тело — noop:
    иначе restore_menu снова создаёт пункты (remove_nn_hub_menu он пропускает).
    """
    return


def remove_neural_networks_hub_menu(apps, schema_editor):
    """Удаляет элементы меню и ролевые группы модуля neural_networks_hub."""
    MenuItem = apps.get_model('cms_adp', 'MenuItem')
    RoleGroup = apps.get_model('cms_adp', 'RoleGroup')
    MenuItem.objects.filter(module_source='modules/neural_networks_hub').delete()
    RoleGroup.objects.filter(name__in=[ROLE_GROUP_TEACHER, ROLE_GROUP_STUDENT]).delete()


def remove_nn_hub_menu(apps, schema_editor):
    MenuItem = apps.get_model('cms_adp', 'MenuItem')
    RoleGroup = apps.get_model('cms_adp', 'RoleGroup')
    MenuItem.objects.filter(module_source='modules/neural_networks_hub').delete()
    RoleGroup.objects.filter(
        name__in=[ROLE_GROUP_TEACHER, ROLE_GROUP_STUDENT]
    ).delete()


def update_shortcodes_module_source(apps, schema_editor):
    MenuItem = apps.get_model('cms_adp', 'MenuItem')
    MenuItem.objects.filter(module_source='core/shortcodes').update(module_source='cms_shortcodes')


def reverse_shortcodes_module_source(apps, schema_editor):
    MenuItem = apps.get_model('cms_adp', 'MenuItem')
    MenuItem.objects.filter(module_source='cms_shortcodes').update(module_source='core/shortcodes')


def update_bi_module_source(apps, schema_editor):
    MenuItem = apps.get_model('cms_adp', 'MenuItem')
    MenuItem.objects.filter(module_source='core/bi').update(module_source='modules/bi_analysis')


def reverse_bi_module_source(apps, schema_editor):
    MenuItem = apps.get_model('cms_adp', 'MenuItem')
    MenuItem.objects.filter(module_source='modules/bi_analysis').update(module_source='core/bi')


def remove_filemanager_menu(apps, schema_editor):
    MenuItem = apps.get_model('cms_adp', 'MenuItem')
    MenuItem.objects.filter(route_name='FileManager').delete()


def group_to_route(apps, schema_editor):
    MenuItem = apps.get_model('cms_adp', 'MenuItem')
    MenuItem.objects.filter(item_type='group').update(item_type='route')


def remove_security_settings_menu(apps, schema_editor):
    """Удаляет пункт меню SecuritySettings, если он есть. Идемпотентно."""
    MenuItem = apps.get_model('cms_adp', 'MenuItem')
    MenuItem.objects.filter(route_name='SecuritySettings').delete()


def set_site_settings_menu_admin_only(apps, schema_editor):
    MenuItem = apps.get_model('cms_adp', 'MenuItem')

    settings_root = MenuItem.objects.filter(route_name='Settings').first()
    if not settings_root:
        return

    ids_to_update = {settings_root.id}
    to_process = [settings_root.id]

    while to_process:
        child_ids = list(
            MenuItem.objects.filter(parent_id__in=to_process).values_list('id', flat=True)
        )
        ids_to_update.update(child_ids)
        to_process = child_ids

    MenuItem.objects.filter(id__in=ids_to_update).update(is_admin_only=True)


def reverse_site_settings_menu_admin_only(apps, schema_editor):
    MenuItem = apps.get_model('cms_adp', 'MenuItem')

    settings_root = MenuItem.objects.filter(route_name='Settings').first()
    if not settings_root:
        return

    ids_to_update = {settings_root.id}
    to_process = [settings_root.id]

    while to_process:
        child_ids = list(
            MenuItem.objects.filter(parent_id__in=to_process).values_list('id', flat=True)
        )
        ids_to_update.update(child_ids)
        to_process = child_ids

    MenuItem.objects.filter(id__in=ids_to_update).update(is_admin_only=False)


def remove_legacy_site_content_menu(apps, schema_editor):
    MenuItem = apps.get_model('cms_adp', 'MenuItem')
    MenuItem.objects.filter(module_source__in=REMOVED_MODULE_SOURCES).delete()
    MenuItem.objects.filter(route_name__in=REMOVED_ROUTE_NAMES).delete()


def move_theme_editor_under_settings(apps, schema_editor):
    MenuItem = apps.get_model('cms_adp', 'MenuItem')

    settings_item = MenuItem.objects.filter(route_name='Settings').first()
    theme_item = MenuItem.objects.filter(route_name='ThemeEditor').first()
    if not settings_item or not theme_item:
        return

    theme_item.parent = settings_item
    theme_item.order = 10
    theme_item.is_admin_only = True
    if not theme_item.icon:
        theme_item.icon = 'Palette'
    theme_item.save()


def restore_theme_editor_top_level(apps, schema_editor):
    MenuItem = apps.get_model('cms_adp', 'MenuItem')

    theme_item = MenuItem.objects.filter(route_name='ThemeEditor').first()
    if not theme_item:
        return

    theme_item.parent = None
    theme_item.order = 11
    theme_item.save()


def restructure_site_settings_menu(apps, schema_editor):
    pass


def _ensure_admin_panel_children(cms, MenuItem, admin_panel):
    users_menu = MenuItem.objects.filter(route_name='UsersPanel', parent=admin_panel).first()
    if not users_menu:
        users_menu = cms.create_group(
            'Пользователи',
            'UsersPanel',
            icon='Users',
            parent=admin_panel,
            order=10,
            is_admin_only=True,
        )

    if not MenuItem.objects.filter(parent=users_menu, route_name='OnlineUsersPanel').exists():
        cms.create_route('В сети', 'OnlineUsersPanel', parent=users_menu, is_admin_only=True)

    admin_routes = [
        ('Роли', 'CategoriesPanel'),
        ('Ролевые группы', 'GroupsPanel'),
        ('Политики и права', 'PermissionsPanel'),
        ('Ограничения', 'LiminationPanel'),
        ('Управление меню', 'MenuPanel'),
    ]
    for order, (name, route_name) in enumerate(admin_routes, start=20):
        if not MenuItem.objects.filter(parent=admin_panel, route_name=route_name).exists():
            cms.create_route(
                name,
                route_name,
                parent=admin_panel,
                order=order,
                is_admin_only=True,
            )


def restore_admin_panel_menu(apps, schema_editor):
    from src.core.cms.adp.menu.migration_utils import MenuMigrationHelper

    MenuItem = apps.get_model('cms_adp', 'MenuItem')
    settings = MenuItem.objects.filter(route_name='Settings').first()
    if not settings:
        return

    cms = MenuMigrationHelper(apps, 'core/cms')

    admin_panel = MenuItem.objects.filter(route_name='AdminPanel').first()
    if not admin_panel:
        admin_panel = cms.create_group(
            'Админ-панель',
            'AdminPanel',
            icon='KeySquare',
            parent=settings,
            order=10,
            is_admin_only=True,
        )
    else:
        admin_panel.parent = settings
        admin_panel.order = 10
        admin_panel.is_admin_only = True
        admin_panel.save()

    theme_item = MenuItem.objects.filter(route_name='ThemeEditor').first()
    if theme_item:
        theme_item.parent = settings
        theme_item.order = 20
        theme_item.name = 'Темы оформления'
        theme_item.is_admin_only = True
        theme_item.save()
        MenuItem.objects.filter(route_name='ThemeEditor').exclude(id=theme_item.id).delete()
    else:
        cms.create_route(
            'Темы оформления',
            'ThemeEditor',
            parent=settings,
            icon='Palette',
            order=20,
            is_admin_only=True,
        )

    MenuItem.objects.filter(route_name='ThemeSettings').delete()

    _ensure_admin_panel_children(cms, MenuItem, admin_panel)


def remove_online_users_menu(apps, schema_editor):
    MenuItem = apps.get_model('cms_adp', 'MenuItem')
    MenuItem.objects.filter(route_name='OnlineUsersPanel').delete()


def rename_site_settings_menu_to_system(apps, schema_editor):
    MenuItem = apps.get_model('cms_adp', 'MenuItem')
    MenuItem.objects.filter(route_name='Settings', name='Настройки сайта').update(
        name='Настройки системы',
    )


def reverse_rename_site_settings_menu_to_system(apps, schema_editor):
    MenuItem = apps.get_model('cms_adp', 'MenuItem')
    MenuItem.objects.filter(route_name='Settings', name='Настройки системы').update(
        name='Настройки сайта',
    )


def remove_users_all_submenu(apps, schema_editor):
    MenuItem = apps.get_model('cms_adp', 'MenuItem')
    MenuItem.objects.filter(route_name='UsersPanel', name='Все').delete()


def flatten_user_account_menu(apps, schema_editor):
    MenuItem = apps.get_model('cms_adp', 'MenuItem')

    user_menu = MenuItem.objects.filter(
        module_source='core/cms',
        name='Личный кабинет',
    ).first()
    if user_menu is None:
        return

    MenuItem.objects.filter(parent=user_menu, route_name='Account').delete()

    user_menu.route_name = 'Account'
    user_menu.save(update_fields=['route_name'])


def restore_user_account_menu(apps, schema_editor):
    from src.core.cms.adp.menu.migration_utils import MenuMigrationHelper

    MenuItem = apps.get_model('cms_adp', 'MenuItem')
    user_menu = MenuItem.objects.filter(
        module_source='core/cms',
        name='Личный кабинет',
    ).first()
    if user_menu is None:
        return

    user_menu.route_name = 'User'
    user_menu.save(update_fields=['route_name'])

    cms = MenuMigrationHelper(apps, 'core/cms')
    cms.create_route('Профиль', 'Account', parent=user_menu)


def add_audit_menu(apps, schema_editor):
    MenuItem = apps.get_model('cms_adp', 'MenuItem')

    admin_panel = MenuItem.objects.filter(route_name='AdminPanel').first()
    if admin_panel is None:
        return

    if MenuItem.objects.filter(route_name=ROUTE_NAME).exists():
        return

    from django.db.models import Max
    max_order = MenuItem.objects.filter(parent=admin_panel).aggregate(
        Max('order')
    )['order__max'] or 0

    MenuItem.objects.create(
        name='Журнал действий',
        route_name=ROUTE_NAME,
        icon='ScrollText',
        item_type='route',
        parent=admin_panel,
        order=max_order + 10,
        is_active=True,
        is_admin_only=True,
        module_source=MODULE_SOURCE,
    )


def remove_audit_menu(apps, schema_editor):
    MenuItem = apps.get_model('cms_adp', 'MenuItem')
    MenuItem.objects.filter(route_name=ROUTE_NAME).delete()


def consolidate_access_menu(apps, schema_editor):
    MenuItem = apps.get_model('cms_adp', 'MenuItem')

    permissions_item = MenuItem.objects.filter(route_name='PermissionsPanel').first()
    limitations_item = MenuItem.objects.filter(route_name='LiminationPanel').first()

    preserved_order = None
    preserved_parent = None

    if permissions_item is not None:
        preserved_order = permissions_item.order
        preserved_parent = permissions_item.parent
        permissions_item.name = 'Доступ и права'
        permissions_item.route_name = NEW_ROUTE_NAME
        permissions_item.save(update_fields=['name', 'route_name'])
    elif limitations_item is not None:
        preserved_order = limitations_item.order
        preserved_parent = limitations_item.parent
        limitations_item.name = 'Доступ и права'
        limitations_item.route_name = NEW_ROUTE_NAME
        limitations_item.save(update_fields=['name', 'route_name'])

    MenuItem.objects.filter(
        route_name__in=['LiminationPanel', 'ModulePagePermissionsPanel'],
    ).delete()

    admin_panel = MenuItem.objects.filter(route_name='AdminPanel').first()
    parent = preserved_parent or admin_panel

    if parent is not None and not MenuItem.objects.filter(route_name=NEW_ROUTE_NAME).exists():
        from django.db.models import Max

        max_order = MenuItem.objects.filter(parent=parent).aggregate(
            Max('order'),
        )['order__max'] or 0

        MenuItem.objects.create(
            name='Доступ и права',
            route_name=NEW_ROUTE_NAME,
            icon='Shield',
            item_type='route',
            parent=parent,
            order=preserved_order if preserved_order is not None else max_order + 10,
            is_active=True,
            is_admin_only=True,
            module_source='core/cms',
        )


def restore_access_menu(apps, schema_editor):
    MenuItem = apps.get_model('cms_adp', 'MenuItem')

    access_item = MenuItem.objects.filter(route_name=NEW_ROUTE_NAME).first()
    if access_item is None:
        return

    access_item.name = 'Политики и права'
    access_item.route_name = 'PermissionsPanel'
    access_item.save(update_fields=['name', 'route_name'])

    admin_panel = access_item.parent
    if admin_panel is None:
        return

    if not MenuItem.objects.filter(route_name='LiminationPanel').exists():
        MenuItem.objects.create(
            name='Ограничения',
            route_name='LiminationPanel',
            icon='Lock',
            item_type='route',
            parent=admin_panel,
            order=access_item.order + 10,
            is_active=True,
            is_admin_only=True,
            module_source='core/cms',
        )


def ensure_user_extension_columns(apps, schema_editor):
    from django.contrib.auth import get_user_model
    from django.db import connection

    vendor = connection.vendor
    table_name = get_user_model()._meta.db_table

    with connection.cursor() as cursor:
        _add_column_if_missing(
            cursor,
            vendor,
            table_name,
            'middle_name',
            'VARCHAR(150) NULL',
        )
        public_id_sql = 'TEXT NULL' if vendor == 'sqlite' else 'UUID NULL'
        _add_column_if_missing(
            cursor,
            vendor,
            table_name,
            'public_id',
            public_id_sql,
        )

        if vendor == 'postgresql':
            cursor.execute(
                f'CREATE UNIQUE INDEX IF NOT EXISTS auth_user_public_id_uniq ON "{table_name}" (public_id)'
            )
            cursor.execute(
                f'UPDATE "{table_name}" SET public_id = gen_random_uuid() WHERE public_id IS NULL'
            )
        else:
            cursor.execute(f'SELECT id FROM "{table_name}" WHERE public_id IS NULL')
            for (user_id,) in cursor.fetchall():
                cursor.execute(
                    f'UPDATE "{table_name}" SET public_id = %s WHERE id = %s',
                    [str(uuid.uuid4()), user_id],
                )


def noop_reverse(apps, schema_editor):
    pass


def remove_fork_auth_migration_records(apps, schema_editor):
    from django.db import connection

    placeholders = ', '.join(['%s'] * len(FORK_AUTH_MIGRATIONS))
    with connection.cursor() as cursor:
        cursor.execute(
            f'DELETE FROM django_migrations WHERE app = %s AND name IN ({placeholders})',
            ['auth', *FORK_AUTH_MIGRATIONS],
        )


def migrate_user_content_type(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')

    old_ct = ContentType.objects.filter(app_label='auth', model='user').first()
    new_ct, _ = ContentType.objects.get_or_create(
        app_label='cms_adp',
        model='ergouser',
    )

    if old_ct is None:
        return

    if old_ct.pk != new_ct.pk:
        Permission.objects.filter(content_type_id=old_ct.pk).update(content_type_id=new_ct.pk)
        old_ct.delete()
    else:
        old_ct.app_label = 'cms_adp'
        old_ct.model = 'ergouser'
        old_ct.save(update_fields=['app_label', 'model'])


def remove_graduate_employment(apps, schema_editor):
    MenuItem = apps.get_model('cms_adp', 'MenuItem')
    ModulePermission = apps.get_model('cms_adp', 'ModulePermission')
    MenuItem.objects.filter(module_source=GRADUATE_EMPLOYMENT_MODULE_SOURCE).delete()
    ModulePermission.objects.filter(module_name=MODULE_NAME).delete()


def drop_graduate_employment_schema(apps, schema_editor):
    connection = schema_editor.connection
    table_names = connection.introspection.table_names()
    prefix = 'graduate_employment_'
    for table in table_names:
        if table.startswith(prefix):
            schema_editor.execute(f'DROP TABLE IF EXISTS "{table}" CASCADE')

    with connection.cursor() as cursor:
        cursor.execute("DELETE FROM django_migrations WHERE app = %s", ['graduate_employment'])


class Migration(migrations.Migration):

    # ErgoUser в state в начале squash (до FK на AUTH_USER_MODEL).
    # Без swappable_dependency на AUTH_USER: иначе цикл со settings squash.
    # Таблица auth_user: create_model только если ещё нет (legacy auth.User).
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ErgoUser',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('password', models.CharField(max_length=128, verbose_name='password')),
                        ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                        ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                        ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                        ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                        ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                        ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                        ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                        ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                        ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                        ('middle_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Отчество')),
                        ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='public id')),
                        ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                        ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                    ],
                    options={
                        'verbose_name': 'пользователь',
                        'verbose_name_plural': 'пользователи',
                        'db_table': 'auth_user',
                        'swappable': 'AUTH_USER_MODEL',
                    },
                    managers=[
                        ('objects', django.contrib.auth.models.UserManager()),
                    ],
                ),
            ],
            database_operations=[
                migrations.RunPython(ensure_ergo_user_table, noop_reverse),
            ],
        ),
        migrations.CreateModel(
            name='EmailConfirmationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('laptop', 'Laptop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], max_length=20)),
                ('device_name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'device_name', 'ip_address')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(default='ru', max_length=10)),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=50)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('profile_visibility', models.CharField(choices=[('public', 'Публичный'), ('private', 'Приватный'), ('friends', 'Только друзья')], default='public', max_length=10)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adp_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_system', models.BooleanField(default=False, verbose_name='Системная роль')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'ordering': ['name'],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='RoleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_role', models.ForeignKey(limit_choices_to={'is_system': False}, on_delete=django.db.models.deletion.CASCADE, related_name='role_groups', to='cms_adp.role', verbose_name='Родительская роль')),
            ],
            options={
                'verbose_name': 'Ролевая группа',
                'verbose_name_plural': 'Ролевые группы',
                'ordering': ['name'],
                'unique_together': {('name', 'parent_role')},
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название политики')),
                ('policy_type', models.CharField(choices=[('url', 'Доступ к URL'), ('component', 'Доступ к компоненту')], default='url', max_length=20, verbose_name='Тип политики')),
                ('action', models.CharField(choices=[('allow', 'Разрешить'), ('deny', 'Запретить')], default='allow', max_length=10, verbose_name='Действие')),
                ('resource_path', models.CharField(max_length=500, verbose_name='Путь к ресурсу')),
                ('is_pattern', models.BooleanField(default=False, verbose_name='Использовать шаблон')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('priority', models.IntegerField(default=0, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='cms_adp.role', verbose_name='Роль')),
                ('role_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='cms_adp.rolegroup', verbose_name='Ролевая группа')),
            ],
            options={
                'verbose_name': 'Политика',
                'verbose_name_plural': 'Политики',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100, verbose_name='Название модуля')),
                ('permission_key', models.CharField(max_length=100, verbose_name='Ключ разрешения')),
                ('permission_name', models.CharField(max_length=200, verbose_name='Название разрешения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_granted', models.BooleanField(default=False, verbose_name='Предоставлено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='cms_adp.rolegroup', verbose_name='Ролевая группа')),
            ],
            options={
                'verbose_name': 'Разрешение модуля',
                'verbose_name_plural': 'Разрешения модулей',
                'unique_together': {('module_name', 'permission_key', 'role_group')},
                'ordering': ['module_name', 'permission_key'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Назначил')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='cms_adp.role', verbose_name='Роль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('role_groups', models.ManyToManyField(blank=True, related_name='user_assignments', to='cms_adp.rolegroup', verbose_name='Ролевые группы')),
            ],
            options={
                'verbose_name': 'Роль пользователя',
                'verbose_name_plural': 'Роли пользователей',
                'unique_together': {('user', 'role')},
            },
        ),
        migrations.RunPython(
            code=create_system_roles,
            reverse_code=delete_system_roles,
        ),
        migrations.RunPython(
            code=remove_middle_name_field_safe,
            reverse_code=add_middle_name_field_back,
        ),
        migrations.CreateModel(
            name='MenuSeparator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название разделителя')),
                ('before_order', models.PositiveIntegerField(help_text='Разделитель будет отображаться перед элементами с этим порядком', verbose_name='Перед порядком')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Разделитель меню',
                'verbose_name_plural': 'Разделители меню',
                'ordering': ['before_order'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('route_name', models.CharField(blank=True, help_text='Имя маршрута из Vue Router (например: User, Settings, BI)', max_length=100, null=True, verbose_name='Имя маршрута Vue')),
                ('icon', models.CharField(blank=True, help_text='Название иконки из Lucide (например: CircleUserRound, UserCog)', max_length=50, null=True, verbose_name='Иконка')),
                ('item_type', models.CharField(choices=[('route', 'Маршрут Vue'), ('group', 'Группа'), ('offcanvas', 'Боковая панель'), ('external', 'Внешняя ссылка')], default='route', max_length=20, verbose_name='Тип элемента')),
                ('page', models.CharField(blank=True, help_text='Для BI модуля: datasets, connections, charts, dashboards', max_length=50, null=True, verbose_name='Страница боковой панели')),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='Внешняя ссылка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_admin_only', models.BooleanField(default=False, verbose_name='Только для администраторов')),
                ('module_source', models.CharField(blank=True, help_text='Путь к модулю (например: core/cms, modules/bi)', max_length=100, null=True, verbose_name='Модуль-источник')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_role_groups', models.ManyToManyField(blank=True, related_name='menu_items', to='cms_adp.rolegroup', verbose_name='Разрешённые ролевые группы')),
                ('allowed_roles', models.ManyToManyField(blank=True, help_text='Если не выбрано ни одной роли, доступно всем', related_name='menu_items', to='cms_adp.role', verbose_name='Разрешённые роли')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms_adp.menuitem', verbose_name='Родительский элемент')),
            ],
            options={
                'verbose_name': 'Элемент меню',
                'verbose_name_plural': 'Элементы меню',
                'ordering': ['order', 'name'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MenuAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, verbose_name='Время доступа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_access_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='cms_adp.menuitem', verbose_name='Элемент меню')),
            ],
            options={
                'verbose_name': 'Лог доступа к меню',
                'verbose_name_plural': 'Логи доступа к меню',
                'ordering': ['-accessed_at'],
                'default_permissions': (),
            },
        ),
        migrations.RunPython(
            code=populate_core_menu,
            reverse_code=reverse_populate_core_menu,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='Оставьте пустым для автоматического определения', null=True, verbose_name='Порядок'),
        ),
        migrations.RunPython(
            code=add_theme_editor_menu,
            reverse_code=remove_theme_editor_menu,
        ),
        migrations.RunPython(
            code=add_neural_networks_hub_menu,
            reverse_code=remove_neural_networks_hub_menu,
        ),
        migrations.RunPython(
            code=remove_nn_hub_menu,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=update_shortcodes_module_source,
            reverse_code=reverse_shortcodes_module_source,
        ),
        migrations.RunPython(
            code=update_bi_module_source,
            reverse_code=reverse_bi_module_source,
        ),
        migrations.RunPython(
            code=remove_filemanager_menu,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=group_to_route,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='item_type',
            field=models.CharField(choices=[('route', 'Маршрут Vue'), ('offcanvas', 'Боковая панель'), ('external', 'Внешняя ссылка')], default='route', max_length=20, verbose_name='Тип элемента'),
        ),
        migrations.RunPython(
            code=remove_security_settings_menu,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.CreateModel(
            name='RegistrationInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Токен')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Примечание')),
                ('expires_at', models.DateTimeField(verbose_name='Действует до')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использовано')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='Отозвано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_registration_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Пригласил')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_invitation', to=settings.AUTH_USER_MODEL, verbose_name='Зарегистрировался')),
            ],
            options={
                'verbose_name': 'Приглашение на регистрацию',
                'verbose_name_plural': 'Приглашения на регистрацию',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(
            code=set_site_settings_menu_admin_only,
            reverse_code=reverse_site_settings_menu_admin_only,
        ),
        migrations.AddField(
            model_name='userdevice',
            name='outstanding_token_jti',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='JTI refresh-токена'),
        ),
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_count', models.PositiveIntegerField(default=0, verbose_name='Число WS-подключений')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Онлайн-статус пользователя',
                'verbose_name_plural': 'Онлайн-статусы пользователей',
            },
        ),
        migrations.RunPython(
            code=remove_legacy_site_content_menu,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=add_theme_editor_menu,
            reverse_code=remove_theme_editor_menu,
        ),
        migrations.RunPython(
            code=move_theme_editor_under_settings,
            reverse_code=restore_theme_editor_top_level,
        ),
        migrations.RunPython(
            code=restructure_site_settings_menu,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=restore_admin_panel_menu,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=remove_online_users_menu,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=rename_site_settings_menu_to_system,
            reverse_code=reverse_rename_site_settings_menu_to_system,
        ),
        migrations.CreateModel(
            name='UserProfileChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Отчество')),
                ('comment', models.CharField(blank=True, default='', max_length=500, verbose_name='Комментарий пользователя')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('admin_comment', models.CharField(blank=True, default='', max_length=500, verbose_name='Комментарий администратора')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_profile_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='Обработал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Заявка на изменение данных профиля',
                'verbose_name_plural': 'Заявки на изменение данных профиля',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='cms_adp_use_user_id_a313df_idx')],
            },
        ),
        migrations.RunPython(
            code=remove_users_all_submenu,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RunPython(
            code=flatten_user_account_menu,
            reverse_code=restore_user_account_menu,
        ),
        migrations.AddField(
            model_name='userprofilechangerequest',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон'),
        ),
        migrations.RunPython(
            code=add_audit_menu,
            reverse_code=remove_audit_menu,
        ),
        migrations.RunPython(
            code=consolidate_access_menu,
            reverse_code=restore_access_menu,
        ),
        migrations.RunPython(
            code=ensure_user_extension_columns,
            reverse_code=noop_reverse,
        ),
        migrations.RunPython(
            code=remove_fork_auth_migration_records,
            reverse_code=noop_reverse,
        ),
        migrations.RunPython(
            code=migrate_user_content_type,
            reverse_code=noop_reverse,
        ),
        migrations.RunPython(
            code=remove_graduate_employment,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=drop_graduate_employment_schema,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
    ]
