# Generated by Django 5.2.8.dev20251127143045 on 2025-12-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_adp', '0007_populate_core_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='Оставьте пустым для автоматического определения', null=True, verbose_name='Порядок'),
        ),
    ]
