# Generated by Django 5.2.8 on 2026-03-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_adp', '0015_menuitem_remove_group_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_type',
            field=models.CharField(choices=[('route', 'Маршрут Vue'), ('offcanvas', 'Боковая панель'), ('external', 'Внешняя ссылка')], default='route', max_length=20, verbose_name='Тип элемента'),
        ),
    ]
