# Generated by Django 5.2.8 on 2026-07-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_adp', '0030_userprofilechangerequest_email'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userprofilechangerequest',
            new_name='cms_adp_use_user_id_a313df_idx',
            old_name='cms_adp_use_user_id_status_idx',
        ),
    ]
