# Generated by Django 5.2.16 on 2026-07-26 07:09

from django.db import migrations


def copy_profile_avatar_to_user_avatar(apps, schema_editor):
    """Перенос непустого UserProfile.avatar в settings.UserAvatar перед удалением поля."""
    UserProfile = apps.get_model('cms_adp', 'UserProfile')
    UserAvatar = apps.get_model('settings', 'UserAvatar')

    for profile in UserProfile.objects.exclude(avatar='').exclude(avatar__isnull=True).iterator():
        avatar_name = profile.avatar.name if profile.avatar else None
        if not avatar_name:
            continue
        if UserAvatar.objects.filter(user_id=profile.user_id).exists():
            continue
        UserAvatar.objects.create(user_id=profile.user_id, image=avatar_name)


class Migration(migrations.Migration):

    dependencies = [
        ('cms_adp', '0044_remove_userprofile_email_notifications'),
        ('settings', '0007_useravatar'),
    ]

    operations = [
        migrations.RunPython(copy_profile_avatar_to_user_avatar, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
    ]
