# Generated by Django 5.2.16 on 2026-07-27 14:52

import src.core.cms.adp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_adp', '0045_remove_legacy_settings_and_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('fr', 'Français')], default=src.core.cms.adp.models._default_user_language, max_length=10),
        ),
    ]
