# Generated by Django 5.2.16 on 2026-07-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_adp', '0048_consolidate_action_log_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='module_source',
            field=models.CharField(blank=True, help_text='Путь к модулю (core/… или modules/<name>)', max_length=100, null=True, verbose_name='Модуль-источник'),
        ),
    ]
