# Generated by Django 5.2.16 on 2026-07-31 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_adp', '0050_admin_submenu_icons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuaccesslog',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='menuaccesslog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='allowed_role_groups',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='allowed_roles',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='parent',
        ),
        migrations.DeleteModel(
            name='MenuSeparator',
        ),
        migrations.DeleteModel(
            name='MenuAccessLog',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
