# Generated by Django 5.2.16 on 2026-07-31 11:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_adp', '0051_remove_menuaccesslog_menu_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSeparator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('name', models.CharField(max_length=100, verbose_name='Название разделителя')),
                ('before_order', models.PositiveIntegerField(help_text='Разделитель будет отображаться перед элементами с этим порядком', verbose_name='Перед порядком')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Разделитель меню',
                'verbose_name_plural': 'Разделители меню',
                'ordering': ['before_order'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('route_name', models.CharField(blank=True, help_text='Имя маршрута из Vue Router (например: User, Settings, BI)', max_length=100, null=True, verbose_name='Имя маршрута Vue')),
                ('icon', models.CharField(blank=True, help_text='Название иконки из Lucide (например: CircleUserRound, UserCog)', max_length=50, null=True, verbose_name='Иконка')),
                ('item_type', models.CharField(choices=[('route', 'Маршрут Vue'), ('offcanvas', 'Боковая панель'), ('external', 'Внешняя ссылка')], default='route', max_length=20, verbose_name='Тип элемента')),
                ('page', models.CharField(blank=True, help_text='Для BI модуля: datasets, connections, charts, dashboards', max_length=50, null=True, verbose_name='Страница боковой панели')),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='Внешняя ссылка')),
                ('order', models.PositiveIntegerField(blank=True, help_text='Оставьте пустым для автоматического определения', null=True, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_admin_only', models.BooleanField(default=False, verbose_name='Только для администраторов')),
                ('module_source', models.CharField(blank=True, help_text='Путь к модулю (core/… или modules/<name>)', max_length=100, null=True, verbose_name='Модуль-источник')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_role_groups', models.ManyToManyField(blank=True, related_name='menu_items', to='cms_adp.rolegroup', verbose_name='Разрешённые ролевые группы')),
                ('allowed_roles', models.ManyToManyField(blank=True, help_text='Если не выбрано ни одной роли, доступно всем', related_name='menu_items', to='cms_adp.role', verbose_name='Разрешённые роли')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms_adp.menuitem', verbose_name='Родительский элемент')),
            ],
            options={
                'verbose_name': 'Элемент меню',
                'verbose_name_plural': 'Элементы меню',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, verbose_name='Время доступа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_access_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='cms_adp.menuitem', verbose_name='Элемент меню')),
            ],
            options={
                'verbose_name': 'Лог доступа к меню',
                'verbose_name_plural': 'Логи доступа к меню',
                'ordering': ['-accessed_at'],
            },
        ),
    ]
