# Generated by Django 5.2.16 on 2026-07-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_adp', '0054_menu_catalog_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='Эффективный порядок (материализация layout)', null=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='menuseparator',
            name='before_order',
            field=models.PositiveIntegerField(help_text='Запасной вариант: перед элементами с этим порядком', verbose_name='Перед порядком'),
        ),
    ]
