# Generated by Django 5.2.16 on 2026-08-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_adp', '0056_restore_menu_after_catalog_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfirmationcode',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
