# Generated by Django 5.2.16 on 2026-08-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_adp', '0058_remove_neural_networks_hub_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuseparator',
            name='allowed_role_groups',
            field=models.ManyToManyField(blank=True, related_name='menu_separators', to='cms_adp.rolegroup', verbose_name='Разрешённые ролевые группы'),
        ),
        migrations.AddField(
            model_name='menuseparator',
            name='allowed_roles',
            field=models.ManyToManyField(blank=True, help_text='Если не выбрано ни одной роли, доступно всем', related_name='menu_separators', to='cms_adp.role', verbose_name='Разрешённые роли'),
        ),
        migrations.AddField(
            model_name='menuseparator',
            name='is_admin_only',
            field=models.BooleanField(default=False, verbose_name='Только для администраторов'),
        ),
    ]
