# Generated by Django 5.2.16 on 2026-08-06 11:25
#
# AddField для MenuSeparator (is_admin_only / allowed_*) перенесены в 0056:
# restore_menu там использует живые модели и падал без колонок.
# Операции оставлены пустыми, чтобы не ломать цепочку у уже применивших 0059.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_adp', '0058_remove_neural_networks_hub_menu'),
    ]

    operations = []
