# Generated by Django 5.2.16 on 2026-08-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_adp', '0059_menuseparator_access_acl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(choices=[('url', 'Доступ к URL'), ('api', 'Доступ к сервису'), ('component', 'Доступ к компоненту')], default='url', max_length=20, verbose_name='Тип политики'),
        ),
    ]
