# Generated by Django 5.2.8 on 2026-03-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Редактировалось'),
        ),
    ]
