# Generated by Django 5.2.8 on 2026-03-04 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_messenger', '0002_message_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='core_messenger.message', verbose_name='Ответ на сообщение'),
        ),
    ]
