# Generated by Django 5.2.8.dev20251127143045 on 2025-11-29 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Описание"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дашборд",
                "verbose_name_plural": "Дашборды",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DashboardPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название страницы"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="bi_analysis_bi_dashboards.dashboard",
                        verbose_name="Дашборд",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страница дашборда",
                "verbose_name_plural": "Страницы дашборда",
                "ordering": ["order", "id"],
                "unique_together": {("dashboard", "order")},
            },
        ),
        migrations.CreateModel(
            name="DashboardItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Заголовок", "Заголовок"),
                            ("Текст", "Текст"),
                            ("Чарт", "Чарт"),
                            ("Селектор", "Селектор"),
                        ],
                        max_length=50,
                        verbose_name="Тип элемента",
                    ),
                ),
                ("x", models.IntegerField(default=0, verbose_name="Позиция X")),
                ("y", models.IntegerField(default=0, verbose_name="Позиция Y")),
                ("width", models.IntegerField(default=200, verbose_name="Ширина")),
                ("height", models.IntegerField(default=150, verbose_name="Высота")),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Конфигурация"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="bi_analysis_bi_dashboards.dashboardpage",
                        verbose_name="Страница",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент дашборда",
                "verbose_name_plural": "Элементы дашборда",
                "ordering": ["order", "id"],
            },
        ),
    ]
