# Generated by Django 5.2.8 on 2025-12-26 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('cms_shortcodes', '0001_initial'), ('cms_shortcodes', '0002_cmsshortcodecategory_and_more')]

    dependencies = [
        ('settings', '0017_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CmsShortcodeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CmsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('category_index', models.BooleanField(default=False, help_text='Если True — страница открывается по URL самой категории')),
                ('is_homepage', models.BooleanField(default=False, help_text='Является ли эта страница главной', verbose_name='Главная страница')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='settings.category', verbose_name='Категория страницы')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='pages', to='settings.tag', verbose_name='Теги страницы')),
            ],
        ),
        migrations.CreateModel(
            name='CmsShortcodeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('component_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='cms_shortcodes.cmsshortcodecategory')),
                ('class_list', models.JSONField(blank=True, default=list)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, help_text='Опциональный HTML или текст')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('allow_children', models.BooleanField(default=False, help_text='Можно ли вкладывать в этот компонент другие компоненты')),
                ('icon_name', models.CharField(blank=True, help_text='Имя иконки из lucide-vue-next', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms_shortcodes.cmsshortcodetemplate')),
                ('position', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CmsShortcodeInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_list', models.JSONField(blank=True, default=list)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('position', models.PositiveIntegerField(default=0)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('icon_name', models.CharField(blank=True, max_length=100, null=True)),
                ('allow_children', models.BooleanField(default=False)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='cms_shortcodes.cmspage')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms_shortcodes.cmsshortcodeinstance')),
                ('template', models.ForeignKey(help_text='Шаблон компонента', on_delete=django.db.models.deletion.PROTECT, to='cms_shortcodes.cmsshortcodetemplate')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='SiteLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms_shortcodes.cmsshortcodetemplate')),
                ('header_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms_shortcodes.cmsshortcodetemplate')),
                ('menu_pages', models.ManyToManyField(blank=True, related_name='+', to='cms_shortcodes.cmspage')),
            ],
            options={
                'verbose_name': 'Глобальный Layout',
                'verbose_name_plural': 'Глобальный Layout',
            },
        ),
        migrations.AddConstraint(
            model_name='cmspage',
            constraint=models.UniqueConstraint(condition=models.Q(('category_index', True)), fields=('category',), name='unique_category_index'),
        ),
        migrations.AddConstraint(
            model_name='cmsshortcodeinstance',
            constraint=models.UniqueConstraint(fields=('parent', 'position'), name='unique_position_per_parent'),
        ),
    ]
