# Generated by Django 5.2.8.dev20251127143045 on 2025-11-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Дополнительные данные сессии (file_id для BI и т.д.)",
            ),
        ),
    ]
