# Generated by Django 5.2.8 on 2025-12-07 14:41

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0002_chatsession_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Название документа", max_length=500),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Файл документа (Word, PDF, TXT и т.д.)",
                        null=True,
                        upload_to="rag_documents/",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True,
                        help_text="Тип файла (docx, pdf, txt и т.д.)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Текстовое содержимое документа (извлекается из файла автоматически или вводится вручную)",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Источник документа (URL, путь к файлу и т.д.)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Дополнительные метаданные документа",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_indexed",
                    models.BooleanField(
                        default=False,
                        help_text="Индексирован ли документ (разбит на chunks с embeddings)",
                    ),
                ),
                (
                    "indexed_at",
                    models.DateTimeField(
                        blank=True, help_text="Время последней индексации", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(help_text="Содержимое chunk")),
                (
                    "chunk_index",
                    models.IntegerField(
                        help_text="Индекс chunk в документе (порядковый номер)"
                    ),
                ),
                (
                    "start_char",
                    models.IntegerField(
                        blank=True,
                        help_text="Начальная позиция в исходном документе",
                        null=True,
                    ),
                ),
                (
                    "end_char",
                    models.IntegerField(
                        blank=True,
                        help_text="Конечная позиция в исходном документе",
                        null=True,
                    ),
                ),
                (
                    "embedding",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        help_text="Векторное представление текста (embedding) для поиска по схожести",
                        size=None,
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        help_text="Модель, использованная для генерации embedding",
                        max_length=100,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Дополнительные метаданные chunk",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="ai_assistant.knowledgedocument",
                    ),
                ),
            ],
            options={
                "ordering": ["document", "chunk_index"],
            },
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(
                fields=["user", "-created_at"], name="ai_assistan_user_id_985efb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(
                fields=["is_indexed"], name="ai_assistan_is_inde_2c318f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgechunk",
            index=models.Index(
                fields=["document", "chunk_index"],
                name="ai_assistan_documen_7cedcb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgechunk",
            index=models.Index(
                fields=["embedding_model"], name="ai_assistan_embeddi_a4af15_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="knowledgechunk",
            unique_together={("document", "chunk_index")},
        ),
    ]
