# Generated by Django 5.2.16 on 2026-08-01 18:19

import django.db.migrations.operations.special
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from src.core.settings.services.theme_seed import (
    ACCESSIBILITY_THEME_RENAME_MAP,
    SYSTEM_THEME_RENAME_MAP,
    SYSTEM_THEMES,
    ensure_system_themes,
    rename_system_themes,
)

LEGACY_THEME_INDEX_RENAMES = (
    ('settings_th_module__a1b2c3_idx', 'settings_th_module__48e8e9_idx'),
    ('settings_th_module__d4e5f6_idx', 'settings_th_module__0d2baf_idx'),
)


def create_default_settings(apps, schema_editor):
    SecuritySettings = apps.get_model('settings', 'SecuritySettings')
    MediaSettings = apps.get_model('settings', 'MediaSettings')
    PermalinkSettings = apps.get_model('settings', 'PermalinkSettings')
    EmailSettings = apps.get_model('settings', 'EmailSettings')

    # Настройки безопасности
    SecuritySettings.objects.create(
        enable_backup=True,
        last_backup=None
    )

    # Настройки медиа
    MediaSettings.objects.create(
        max_upload_size=5 * 1024 * 1024,  # 5MB
        allowed_file_types="jpg,jpeg,png,gif,svg,mp4,mp3,pdf"
    )

    # Настройки постоянных ссылок
    PermalinkSettings.objects.create(
        structure="/%year%/%month%/%slug%/"
    )

    # Настройки email
    EmailSettings.objects.create(
        smtp_host="smtp.example.com",
        smtp_port=587,
        use_tls=True,
        username="",
        password="",
        default_from="noreply@example.com"
    )


def create_system_themes(apps, schema_editor):
    Theme = apps.get_model('settings', 'Theme')
    ensure_system_themes(Theme)


def assign_default_pairs(apps, schema_editor):
    Theme = apps.get_model('settings', 'Theme')
    Theme.objects.filter(module_key__isnull=False).update(module_pair='default')


def seed_ai_assistant_themes(apps, schema_editor):
    # Ранее вызывал ensure_builtin_module_themes (no-op). Модульные темы —
    # через POST settings/themes/sync-module-defaults / ensure_module_themes_from_manifests.
    pass


def rename_legacy_theme_indexes(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor != 'postgresql':
        return

    with connection.cursor() as cursor:
        for old_name, new_name in LEGACY_THEME_INDEX_RENAMES:
            cursor.execute(
                """
                SELECT 1
                FROM pg_indexes
                WHERE schemaname = current_schema()
                  AND indexname = %s
                """,
                [old_name],
            )
            if not cursor.fetchone():
                continue

            cursor.execute(
                """
                SELECT 1
                FROM pg_indexes
                WHERE schemaname = current_schema()
                  AND indexname = %s
                """,
                [new_name],
            )
            if cursor.fetchone():
                continue

            cursor.execute(
                f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"',
            )


def seed_accent_system_themes(apps, schema_editor):
    Theme = apps.get_model('settings', 'Theme')
    ensure_system_themes(Theme)


def seed_rich_system_themes(apps, schema_editor):
    Theme = apps.get_model('settings', 'Theme')
    ensure_system_themes(Theme)


def rename_and_seed_system_themes(apps, schema_editor):
    Theme = apps.get_model('settings', 'Theme')
    name_to_description = {spec['name']: spec['description'] for spec in SYSTEM_THEMES}
    rename_system_themes(Theme, SYSTEM_THEME_RENAME_MAP, descriptions=name_to_description)
    ensure_system_themes(Theme)


def seed_accessibility_system_themes(apps, schema_editor):
    Theme = apps.get_model('settings', 'Theme')
    ensure_system_themes(Theme)


def rename_accessibility_theme_names(apps, schema_editor):
    Theme = apps.get_model('settings', 'Theme')
    name_to_description = {spec['name']: spec['description'] for spec in SYSTEM_THEMES}
    rename_system_themes(
        Theme,
        ACCESSIBILITY_THEME_RENAME_MAP,
        descriptions=name_to_description,
    )
    ensure_system_themes(Theme)


def rename_a11y_abbr_theme_names(apps, schema_editor):
    Theme = apps.get_model('settings', 'Theme')
    name_to_description = {spec['name']: spec['description'] for spec in SYSTEM_THEMES}
    rename_system_themes(
        Theme,
        ACCESSIBILITY_THEME_RENAME_MAP,
        descriptions=name_to_description,
    )
    ensure_system_themes(Theme)


def seed_theme_availability(apps, schema_editor):
    Theme = apps.get_model('settings', 'Theme')
    site = Theme.objects.filter(module_key__isnull=True)
    site.filter(is_system=True).update(is_available=True)
    active = site.filter(is_active=True).first()
    if active:
        site.filter(is_default=True).exclude(pk=active.pk).update(is_default=False)
        Theme.objects.filter(pk=active.pk).update(is_default=True, is_available=True)
    else:
        default = site.filter(is_default=True).first()
        if default:
            Theme.objects.filter(pk=default.pk).update(is_active=True, is_available=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):



    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppearanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(default='default', max_length=100, verbose_name='Название темы')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Конфигурация темы')),
            ],
            options={
                'verbose_name': 'Настройки внешнего вида',
                'verbose_name_plural': 'Настройки внешнего вида',
            },
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(blank=True, max_length=255, verbose_name='SMTP Host')),
                ('smtp_port', models.PositiveIntegerField(default=25, verbose_name='SMTP Port')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Use TLS')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='SMTP Username')),
                ('password', models.CharField(blank=True, max_length=255, verbose_name='SMTP Password')),
                ('default_from', models.EmailField(blank=True, max_length=254, verbose_name='Default From Email')),
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
            },
        ),
        migrations.CreateModel(
            name='MediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_upload_size', models.PositiveIntegerField(default=5242880, help_text='Максимальный размер загружаемого файла', verbose_name='Max Upload Size (bytes)')),
                ('allowed_file_types', models.CharField(default='jpg,jpeg,png,gif,svg,mp4,mp3,pdf', help_text='Через запятую, без точек', max_length=255, verbose_name='Allowed File Extensions')),
            ],
            options={
                'verbose_name': 'Media Settings',
                'verbose_name_plural': 'Media Settings',
            },
        ),
        migrations.CreateModel(
            name='PermalinkSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.CharField(default='/%year%/%month%/%slug%/', help_text='Например: /%year%/%month%/%slug%/', max_length=255, verbose_name='URL Structure')),
            ],
            options={
                'verbose_name': 'Permalink Settings',
                'verbose_name_plural': 'Permalink Settings',
            },
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_backup', models.BooleanField(default=True, help_text='Показывать кнопку резервного копирования', verbose_name='Enable Backup')),
                ('last_backup', models.DateTimeField(blank=True, null=True, verbose_name='Last Backup Time')),
            ],
            options={
                'verbose_name': 'Security Settings',
                'verbose_name_plural': 'Security Settings',
            },
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Site', max_length=255, verbose_name='Название сайта')),
                ('site_tagline', models.CharField(blank=True, max_length=255, verbose_name='Tagline')),
                ('site_url', models.URLField(verbose_name='URL сайта')),
                ('admin_email', models.EmailField(max_length=254, verbose_name='Email администратора')),
                ('homepage_type', models.CharField(choices=[('static', 'Статическая страница'), ('latest', 'Последние сообщения')], default='latest', max_length=10, verbose_name='Тип домашней страницы')),
                ('posts_per_page', models.PositiveIntegerField(default=10, verbose_name='Посты на страницу')),
                ('discourage_search_engines', models.BooleanField(default=False, help_text='Запретить индексацию сайта', verbose_name='Discourage Search Engines')),
                ('privacy_policy', models.TextField(blank=True, verbose_name='Политика конфиденциальности')),
                ('roles', models.ManyToManyField(blank=True, help_text='Группы пользователей, доступных в системе', to='auth.group', verbose_name='Роли пользователей')),
            ],
            options={
                'verbose_name': 'Общие настройки',
                'verbose_name_plural': 'Общие настройки',
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('alt_name', models.CharField(blank=True, help_text='Понятное пользователю название файла', max_length=255, verbose_name='Альтернативное название')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='settings.category', verbose_name='Родительская категория')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'unique_together': {('parent', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название тега')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='settings.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('UPDATE', 'Обновление'), ('DELETE', 'Удаление')], max_length=6)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Аудит-журналы',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='settings_au_content_214e6a_idx'), models.Index(fields=['timestamp'], name='settings_au_timesta_8b0650_idx')],
            },
        ),
        migrations.RunPython(
            code=create_default_settings,
        ),
        migrations.AddField(
            model_name='appearancesettings',
            name='theme_config',
            field=models.JSONField(blank=True, default=dict, help_text='JSON с настройками цветов для light и dark тем', verbose_name='Полная конфигурация темы'),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название темы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Автор')),
                ('base_theme', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная')], default='light', help_text='На какой теме основана (влияет на Bootstrap переменные)', max_length=10, verbose_name='Базовая тема')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
                ('is_default', models.BooleanField(default=False, help_text='Использовать как тему по умолчанию', verbose_name='По умолчанию')),
                ('is_system', models.BooleanField(default=False, help_text='Системные темы нельзя удалить', verbose_name='Системная')),
                ('colors', models.JSONField(default=dict, help_text='Кастомные CSS переменные --color-*', verbose_name='Цвета темы')),
                ('bootstrap_colors', models.JSONField(blank=True, default=dict, help_text='Переопределение Bootstrap переменных --bs-*', verbose_name='Bootstrap цвета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['-is_default', '-is_system', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='site_name',
            field=models.CharField(default='ERGOMS', max_length=255, verbose_name='Название сайта'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='GeneralSettings',
        ),
        migrations.DeleteModel(
            name='AppearanceSettings',
        ),
        migrations.RunPython(
            code=create_system_themes,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name='theme',
            name='module_key',
            field=models.CharField(blank=True, help_text='Ключ модуля (kebab-case). Пусто — глобальная тема сайта.', max_length=100, null=True, verbose_name='Модуль'),
        ),
        migrations.AddField(
            model_name='theme',
            name='module_tokens',
            field=models.JSONField(blank=True, default=dict, help_text='Дополнительные CSS-переменные модуля (--module-*)', verbose_name='Токены модуля'),
        ),
        migrations.AddIndex(
            model_name='theme',
            index=models.Index(fields=['module_key', 'is_active'], name='settings_th_module__48e8e9_idx'),
        ),
        migrations.AddIndex(
            model_name='theme',
            index=models.Index(fields=['module_key', 'is_default'], name='settings_th_module__0d2baf_idx'),
        ),
        migrations.AddField(
            model_name='theme',
            name='module_pair',
            field=models.CharField(blank=True, default='', help_text='Связка light+dark вариантов модуля. Пусто — тема сайта.', max_length=64, verbose_name='Пара модульной темы'),
        ),
        migrations.RunPython(
            code=assign_default_pairs,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=seed_ai_assistant_themes,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=rename_legacy_theme_indexes,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=seed_accent_system_themes,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=seed_rich_system_themes,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=rename_and_seed_system_themes,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=seed_accessibility_system_themes,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=rename_accessibility_theme_names,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=rename_a11y_abbr_theme_names,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name='theme',
            name='defaults_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Manifest-данные для сброса модульной темы (заполняется при sync-module-defaults).', verbose_name='Снимок начальных значений'),
        ),
        migrations.DeleteModel(
            name='MediaSettings',
        ),
        migrations.DeleteModel(
            name='PermalinkSettings',
        ),
        migrations.DeleteModel(
            name='SecuritySettings',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.CreateModel(
            name='UserThemePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Предпочтение темы пользователя',
                'verbose_name_plural': 'Предпочтения тем пользователей',
            },
        ),
        migrations.AddField(
            model_name='theme',
            name='is_available',
            field=models.BooleanField(default=False, help_text='Тема доступна всем в каталоге быстрого выбора', verbose_name='В быстром выборе'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Стандарт сайта для пользователей без личного выбора', verbose_name='По умолчанию'),
        ),
        migrations.AddIndex(
            model_name='theme',
            index=models.Index(fields=['module_key', 'is_available'], name='settings_th_module__7988fc_idx'),
        ),
        migrations.AddField(
            model_name='userthemepreference',
            name='favorites',
            field=models.ManyToManyField(blank=True, limit_choices_to={'module_key__isnull': True}, related_name='favorited_by_users', to='settings.theme', verbose_name='Быстрый выбор'),
        ),
        migrations.AddField(
            model_name='userthemepreference',
            name='selected_theme',
            field=models.ForeignKey(blank=True, help_text='Пусто — стандарт сайта', limit_choices_to={'module_key__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by_users', to='settings.theme', verbose_name='Выбранная тема'),
        ),
        migrations.AddField(
            model_name='userthemepreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme_preference', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.RunPython(
            code=seed_theme_availability,
            reverse_code=noop_reverse,
        ),
        migrations.AlterField(
            model_name='theme',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Стандарт системы для пользователей без личного выбора', verbose_name='По умолчанию'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='module_key',
            field=models.CharField(blank=True, help_text='Ключ модуля (kebab-case). Пусто — глобальная тема системы.', max_length=100, null=True, verbose_name='Модуль'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='module_pair',
            field=models.CharField(blank=True, default='', help_text='Связка light+dark вариантов модуля. Пусто — тема системы.', max_length=64, verbose_name='Пара модульной темы'),
        ),
        migrations.AlterField(
            model_name='userthemepreference',
            name='selected_theme',
            field=models.ForeignKey(blank=True, help_text='Пусто — стандарт системы', limit_choices_to={'module_key__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by_users', to='settings.theme', verbose_name='Выбранная тема'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='password',
            field=models.CharField(blank=True, max_length=512, verbose_name='SMTP Password'),
        ),
    ]
