# Generated by Django 5.2.8.dev20251127143045 on 2025-12-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_remove_generalsettings_site_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearancesettings',
            name='theme_config',
            field=models.JSONField(blank=True, default=dict, help_text='JSON с настройками цветов для light и dark тем', verbose_name='Полная конфигурация темы'),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название темы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Автор')),
                ('base_theme', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная')], default='light', help_text='На какой теме основана (влияет на Bootstrap переменные)', max_length=10, verbose_name='Базовая тема')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
                ('is_default', models.BooleanField(default=False, help_text='Использовать как тему по умолчанию', verbose_name='По умолчанию')),
                ('is_system', models.BooleanField(default=False, help_text='Системные темы нельзя удалить', verbose_name='Системная')),
                ('colors', models.JSONField(default=dict, help_text='Кастомные CSS переменные --color-*', verbose_name='Цвета темы')),
                ('bootstrap_colors', models.JSONField(blank=True, default=dict, help_text='Переопределение Bootstrap переменных --bs-*', verbose_name='Bootstrap цвета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['-is_default', '-is_system', 'name'],
            },
        ),
    ]
