# Generated by Django 5.2.8 on 2026-06-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0018_delete_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='site_name',
            field=models.CharField(default='ERGOMS', max_length=255, verbose_name='Название сайта'),
        ),
    ]
