# Generated by Django 5.2.16 on 2026-07-26 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0033_theme_defaults_snapshot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaSettings',
        ),
        migrations.DeleteModel(
            name='PermalinkSettings',
        ),
        migrations.DeleteModel(
            name='SecuritySettings',
        ),
    ]
