# Generated by Django 5.2.16 on 2026-07-26 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0034_remove_legacy_settings_and_userprofile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
