# Generated by Django 5.2.16 on 2026-07-27 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_theme_availability(apps, schema_editor):
    Theme = apps.get_model('settings', 'Theme')
    site = Theme.objects.filter(module_key__isnull=True)
    site.filter(is_system=True).update(is_available=True)
    active = site.filter(is_active=True).first()
    if active:
        site.filter(is_default=True).exclude(pk=active.pk).update(is_default=False)
        Theme.objects.filter(pk=active.pk).update(is_default=True, is_available=True)
    else:
        default = site.filter(is_default=True).first()
        if default:
            Theme.objects.filter(pk=default.pk).update(is_active=True, is_available=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0035_remove_legacy_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserThemePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Предпочтение темы пользователя',
                'verbose_name_plural': 'Предпочтения тем пользователей',
            },
        ),
        migrations.AddField(
            model_name='theme',
            name='is_available',
            field=models.BooleanField(default=False, help_text='Тема доступна всем в каталоге быстрого выбора', verbose_name='В быстром выборе'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Стандарт сайта для пользователей без личного выбора', verbose_name='По умолчанию'),
        ),
        migrations.AddIndex(
            model_name='theme',
            index=models.Index(fields=['module_key', 'is_available'], name='settings_th_module__7988fc_idx'),
        ),
        migrations.AddField(
            model_name='userthemepreference',
            name='favorites',
            field=models.ManyToManyField(blank=True, limit_choices_to={'module_key__isnull': True}, related_name='favorited_by_users', to='settings.theme', verbose_name='Быстрый выбор'),
        ),
        migrations.AddField(
            model_name='userthemepreference',
            name='selected_theme',
            field=models.ForeignKey(blank=True, help_text='Пусто — стандарт сайта', limit_choices_to={'module_key__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by_users', to='settings.theme', verbose_name='Выбранная тема'),
        ),
        migrations.AddField(
            model_name='userthemepreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme_preference', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.RunPython(seed_theme_availability, noop_reverse),
    ]
