# Generated by Django 5.2.16 on 2026-07-28 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0036_theme_is_available_and_user_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Стандарт системы для пользователей без личного выбора', verbose_name='По умолчанию'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='module_key',
            field=models.CharField(blank=True, help_text='Ключ модуля (kebab-case). Пусто — глобальная тема системы.', max_length=100, null=True, verbose_name='Модуль'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='module_pair',
            field=models.CharField(blank=True, default='', help_text='Связка light+dark вариантов модуля. Пусто — тема системы.', max_length=64, verbose_name='Пара модульной темы'),
        ),
        migrations.AlterField(
            model_name='userthemepreference',
            name='selected_theme',
            field=models.ForeignKey(blank=True, help_text='Пусто — стандарт системы', limit_choices_to={'module_key__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by_users', to='settings.theme', verbose_name='Выбранная тема'),
        ),
    ]
