# Generated by Django 5.2.16 on 2026-08-04 09:31

from django.db import migrations, models

# Копия суффиксов из theme_seed_catalog.py — миграции не импортируют
# изменяемый код приложения, чтобы не ломаться при будущих правках каталога.
_LIGHT_SUFFIX = ' · светлая'
_DARK_SUFFIX = ' · тёмная'


def _derive_pair_key(name):
    raw = (name or '').strip()
    if raw.endswith(_DARK_SUFFIX):
        return raw[: -len(_DARK_SUFFIX)].strip()
    if raw.endswith(_LIGHT_SUFFIX):
        return raw[: -len(_LIGHT_SUFFIX)].strip()
    return raw


def backfill_theme_pair(apps, schema_editor):
    """Проставляет theme_pair для существующих системных тем сайта по имени."""
    Theme = apps.get_model('settings', 'Theme')
    site_system_themes = Theme.objects.filter(module_key__isnull=True, is_system=True)
    for theme in site_system_themes:
        pair_key = _derive_pair_key(theme.name)
        if pair_key and theme.theme_pair != pair_key:
            theme.theme_pair = pair_key
            theme.save(update_fields=['theme_pair'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial_squashed_0038_emailsettings_password_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='theme_pair',
            field=models.CharField(blank=True, default='', help_text='Связка light+dark вариантов темы сайта. Пусто — тема без пары.', max_length=100, verbose_name='Пара палитры сайта'),
        ),
        migrations.RunPython(backfill_theme_pair, noop_reverse),
    ]
