# Generated by Django 5.2.8 on 2026-07-04 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
                ('actor_label', models.CharField(blank=True, default='', max_length=255, verbose_name='Инициатор (снимок)')),
                ('source_module', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Модуль-источник')),
                ('action', models.CharField(db_index=True, max_length=128, verbose_name='Действие')),
                ('severity', models.CharField(choices=[('info', 'Информация'), ('security', 'Безопасность'), ('critical', 'Критично')], default='info', max_length=16, verbose_name='Важность')),
                ('entity_type', models.CharField(blank=True, default='', max_length=64, verbose_name='Тип объекта')),
                ('entity_ref', models.CharField(blank=True, default='', max_length=128, verbose_name='Ссылка на объект')),
                ('entity_label', models.CharField(blank=True, default='', max_length=255, verbose_name='Объект (снимок)')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Изменения')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('organization_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='Организация')),
                ('department_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Подразделение')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.CharField(blank=True, default='', max_length=512, verbose_name='User-Agent')),
                ('request_id', models.CharField(blank=True, default='', max_length=64, verbose_name='ID запроса')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
            ],
            options={
                'verbose_name': 'Запись журнала действий',
                'verbose_name_plural': 'Журнал действий',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['source_module', 'action', 'created_at'], name='core_audit__source__3babfa_idx'), models.Index(fields=['actor', 'created_at'], name='core_audit__actor_i_02846b_idx'), models.Index(fields=['organization_id', 'created_at'], name='core_audit__organiz_f0d8a7_idx'), models.Index(fields=['entity_type', 'entity_ref'], name='core_audit__entity__56af7f_idx')],
            },
        ),
    ]
