# Generated by Django 5.2.15 on 2026-07-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_audit', '0003_auditactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='scope',
            field=models.JSONField(blank=True, default=dict, verbose_name='Измерения (scope)'),
        ),
    ]
