# Generated by Django 5.2.15 on 2026-07-21 09:32

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_audit', '0005_backfill_audit_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditevent',
            name='core_audit__organiz_f0d8a7_idx',
        ),
        migrations.RemoveField(
            model_name='auditevent',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='auditevent',
            name='organization_id',
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=django.contrib.postgres.indexes.GinIndex(fields=['scope'], name='audit_scope_gin'),
        ),
    ]
