# Generated by Django 5.2.8 on 2026-01-30 14:36

import src.core.ai_assistant.tp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant_tp', '0001_claim_technologicalprocessdocument'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='technologicalprocessdocument',
            new_name='ai_assistan_user_id_dac1d5_idx',
            old_name='ai_assistan_user_id_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='technologicalprocessdocument',
            new_name='ai_assistan_session_5a42dd_idx',
            old_name='ai_assistan_session_abc123_idx',
        ),
        migrations.AlterField(
            model_name='technologicalprocessdocument',
            name='file',
            field=models.FileField(help_text='Оригинальный файл техпроцесса (DOCX)', upload_to=src.core.ai_assistant.tp.models.tp_document_upload_to),
        ),
    ]
